---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-deploy
  labels:
    type: webapp
spec:
  replicas: 4
  selector:
    matchLabels:
      type: webapp
  template:
    metadata:
      name: nginx-pod
      labels:
        type: webapp
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              hostPort: 8888

