---
version: '3'
services:
  voting-app:
    image: dockersamples/examplevotingapp_vote
    ports:
      - 8080:80
  redis:
    image: redis
    ports:
      - 6379:6379
  worker:
    image: dockersamples/examplevotingapp_worker

  postgres:
    image: postgres
    env:
      POSTGRES_PASSWORD: naresh
    ports:
      -9090:80
  voting-result:
    image: dockersamples/examplevotingapp_result
    ports:
      30008:80