---
apiVersion: v1
kind: Pod
metadata:
  - name: httpdserver-pod
    labels:
      author: naresh
      type: webserver
spec:
  containers:
    - name: httpdserver
      image: httpd
      ports:
        - containerPort: 80
          hostPort: 8080
...