---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: tomcatrs
  labels:
    type: appserver
    author: naresh
spec:
  replicas: 3
  selector:
    matchLabels:
      type: appserver
  template:
    metadata:
      name: tomcatpod
      labels:
        type: appserver
    spec:
      containers:
        - name: myappserver
          image: tomcat
          ports:
            - containerPort: 8080
              hostPort: 9090
...