---
apiVersion: v1
kind: Service
metadata:
  name: result-service
  labels:
    author: naresh
spec:
  type: LoadBalancer
  ports:
    - targetPort: 80
      port: 80
      nodePort: 8080
  selector:
    author: naresh
