---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-app
  labels:
    author: naresh
spec:
  replicas: 3
  selector:
    matchLabels:
      name: result-app
  template:
    metadata:
      name: result-app
      labels:
        name: result-app
    spec:
      containers:
        - name: result-app
          image: dockersamples/examplevotingapp_result
