apiVersion: v1
kind: : Pod
metadata:
  name: vol-pod
  labels:
    author: naresh
spec:
  containers:
    - name: redis
      image: redis
      volumeMounts:
        - name: redis-volume
          mountPath: /data/redis
  volumes:
    - name: redis-volume
      emptyDir: {}
...

