---
apiVersion: v1
kind: Service
metadata:
  name: voting-ser
  labels:
    author: naresh
spec:
 type: LoadBalancer
 ports:
    - targetPort: 80
      port: 80
      nodePort: 9090
 selector:
   author: naresh



